# Generated by Django 2.0.6 on 2018-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfgen',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfgen',
            name='output',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfgen',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
