# Generated by Django 2.0.6 on 2018-06-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_api', '0002_auto_20180606_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfgen',
            old_name='output',
            new_name='rendered_file',
        ),
    ]
