# Generated by Django 2.0.6 on 2018-06-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_api', '0003_auto_20180606_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfgen',
            old_name='url',
            new_name='website',
        ),
    ]
